"""Alembic environment.

Async, because the application's engine is async and maintaining a second sync
driver just for migrations means two connection configurations that can disagree
about SSL, search_path or timeouts.

Three deliberate choices:

* **The URL comes from ``Settings``**, never from ``alembic.ini``. One source of
  truth for where the database is.
* **``target_metadata`` is imported through ``learnos_api.models``**, not through
  the individual model modules. Importing the package is what registers every
  table on ``Base.metadata``; importing modules piecemeal is how a table ends up
  missing from an autogenerated migration.
* **``include_object`` skips the generated search columns.** ``search_tsv`` and
  ``error_tsv`` on ``concept_index`` are Postgres ``GENERATED ALWAYS AS`` columns
  installed by ``knowledge.search.install_full_text``, not SQLAlchemy columns.
  Without this filter, every autogenerate would helpfully offer to drop them.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from learnos_api.config import get_settings
from learnos_api.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

settings = get_settings()
config.set_main_option("sqlalchemy.url", settings.alembic_database_url)

#: Columns Postgres owns, which SQLAlchemy does not model and must not drop.
GENERATED_COLUMNS = {("concept_index", "search_tsv"), ("concept_index", "error_tsv")}


def include_object(object_, name, type_, reflected, compare_to) -> bool:  # noqa: ANN001
    if type_ == "column" and (getattr(object_.table, "name", None), name) in GENERATED_COLUMNS:
        return False
    if type_ == "index" and name and name.endswith(("_tsv", "_trgm")):
        return False
    return True


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting.

    Kept working because a reviewer approving a production migration should be
    able to read the SQL, and `--sql` is the only honest way to show it.
    """
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=True,
        include_object=include_object,
        # Every migration in one transaction per invocation, so a failure halfway
        # through leaves the schema where it started rather than half-migrated.
        transaction_per_migration=False,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=None,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_async_migrations())
